#!/usr/bin/env bash

set -euo pipefail

usage() {
    cat <<EOF
Usage: ${0##*/} NEW_VERSION

Update Cargo.toml and Cargo.lock, commit the version changes, and create
a Git tag. NEW_VERSION must be greater than the current version and
must not include the leading "v".

Two-component versions are accepted and normalized:

  0.2 -> 0.2.0

Example:
  ${0##*/} 7.7.0
EOF
}

die() {
    echo "Error: $*" >&2
    echo "exiting" >&2
    exit 1
}

if [[ $# == 1 && "$1" == "--help" ]]; then
    usage
    exit 0
fi

if [[ $# != 1 || -z "$1" ]]; then
    echo "Error: exactly one NEW_VERSION argument is required." >&2
    echo >&2
    usage >&2
    exit 2
fi

SCRIPT_DIR=$(
    cd "$(dirname "${BASH_SOURCE[0]}")"
    pwd
)

REPO_ROOT=$(
    cd "$SCRIPT_DIR/.."
    pwd
)

cd "$REPO_ROOT"

git rev-parse --is-inside-work-tree >/dev/null 2>&1 ||
    die "this command must run inside a Git working tree"

normalize_version() {
    local supplied=$1
    local major
    local minor
    local patch

    if [[ "$supplied" =~ ^([0-9]+)\.([0-9]+)$ ]]; then
        major=${BASH_REMATCH[1]}
        minor=${BASH_REMATCH[2]}
        patch=0
    elif [[ "$supplied" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
        major=${BASH_REMATCH[1]}
        minor=${BASH_REMATCH[2]}
        patch=${BASH_REMATCH[3]}
    else
        die \
            "version must have the form MAJOR.MINOR or MAJOR.MINOR.PATCH; got '$supplied'"
    fi

    # Convert to decimal integers, removing any leading zeroes.
    major=$((10#$major))
    minor=$((10#$minor))
    patch=$((10#$patch))

    printf '%d.%d.%d\n' "$major" "$minor" "$patch"
}

assert_version_greater() {
    local current
    local proposed

    current=$(normalize_version "$1")
    proposed=$(normalize_version "$2")

    local current_major
    local current_minor
    local current_patch
    local proposed_major
    local proposed_minor
    local proposed_patch

    IFS=. read -r \
        current_major \
        current_minor \
        current_patch \
        <<< "$current"

    IFS=. read -r \
        proposed_major \
        proposed_minor \
        proposed_patch \
        <<< "$proposed"

    if ((proposed_major > current_major)); then
        :
    elif ((proposed_major < current_major)); then
        die "version '$proposed' is not greater than '$current'"
    elif ((proposed_minor > current_minor)); then
        :
    elif ((proposed_minor < current_minor)); then
        die "version '$proposed' is not greater than '$current'"
    elif ((proposed_patch > current_patch)); then
        :
    else
        die "version '$proposed' is not greater than '$current'"
    fi

    echo "Success: $proposed is greater than $current"
}

set_manifest_version() {
    local new_version=$1
    local temporary
    local status

    temporary=$(
        mktemp "${TMPDIR:-/tmp}/bench-hashes-Cargo.toml.XXXXXX"
    )

    awk -v new_version="$new_version" '
        BEGIN {
            in_package = 0
            changed = 0
        }

        /^[[:space:]]*$$package$$[[:space:]]*$/ {
            in_package = 1
            print
            next
        }

        /^[[:space:]]*$$/ {
            in_package = 0
        }

        in_package && /^[[:space:]]*version[[:space:]]*=/ {
            print "version = \"" new_version "\""
            changed++
            next
        }

        {
            print
        }

        END {
            if (changed != 1) {
                exit 42
            }
        }
    ' Cargo.toml > "$temporary" || status=$?

    status=${status:-0}

    if [[ $status -ne 0 ]]; then
        rm -f "$temporary"

        if [[ $status -eq 42 ]]; then
            die \
                "Cargo.toml must contain exactly one version assignment in its [package] section"
        fi

        die "failed to process Cargo.toml with awk"
    fi

    cat "$temporary" > Cargo.toml
    rm -f "$temporary"

    grep -Fqx \
        "version = \"$new_version\"" \
        Cargo.toml ||
        die "Cargo.toml version update did not produce the expected value"
}

update_lock_file() {
    cargo update --workspace --offline
}

NEW_VERSION=$(normalize_version "$1")

# Use the most recent reachable version tag. It does not need to point
# directly at HEAD, because ordinary development commits normally occur
# between releases.
CURRENT_TAG=$(
    git describe \
        --tags \
        --abbrev=0 \
        --match 'v[0-9]*' 2>/dev/null
) || die "no reachable version tag beginning with 'v' was found"

[[ "$CURRENT_TAG" == v* ]] ||
    die "current tag must start with 'v'; got '$CURRENT_TAG'"

CURRENT_VERSION=${CURRENT_TAG#v}

# Tags generated by this script have the form:
#
#   v0.2.0+COMMIT
#
# Compare only the numeric version.
CURRENT_VERSION=${CURRENT_VERSION%%+*}

assert_version_greater "$CURRENT_VERSION" "$NEW_VERSION"

# Generating a release from a dirty tree is a contract violation. Unlike the
# old script, this checks before changing Cargo.toml.
GIT_STATUS=$(
    git status \
        --porcelain=v1 \
        --untracked-files=all
)

[[ -z "$GIT_STATUS" ]] ||
    die "the working tree must be clean before generating a version"

set_manifest_version "$NEW_VERSION"
update_lock_file

git add Cargo.toml Cargo.lock
git commit -m \
    "Update Cargo.toml and Cargo.lock for version $NEW_VERSION"

VERSION_COMMIT=$(git rev-parse HEAD)
FULL_VERSION="${NEW_VERSION}+${VERSION_COMMIT}"

set_manifest_version "$FULL_VERSION"
update_lock_file

git add Cargo.toml Cargo.lock
git commit -m \
    "Update Cargo.toml and Cargo.lock for version $FULL_VERSION"

git tag "v${FULL_VERSION}"

FINAL_COMMIT=$(git rev-parse HEAD)

echo
echo "Created version:"
echo "  package version: $FULL_VERSION"
echo "  Git tag:         v$FULL_VERSION"
echo "  Git commit:      $FINAL_COMMIT"
